/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tech_perforator_unwind_Native */

#ifndef _Included_tech_perforator_unwind_Native
#define _Included_tech_perforator_unwind_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tech_perforator_unwind_Native
 * Method:    unwind0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_tech_perforator_unwind_Native_unwind0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     tech_perforator_unwind_Native
 * Method:    unwindIfZero0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_tech_perforator_unwind_Native_unwindIfZero0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     tech_perforator_unwind_Native
 * Method:    make0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tech_perforator_unwind_Native_make0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
