name: 'Run command'
description: 'Executes specified code in a temporary VM'
inputs:
  target_checkout:
    required: true
    description: 'Absolute path to the repository checkout which needs to be executed. It need not be trusted, but argument value itself must not contain weird characters.'
  script:
    required: true
    description: 'Name of script to be executed (perforator/ci/scripts/${script}.sh must be valid path)'
  start_function_url:
    required: true
    description: 'START_BUILD_FUNCTION_URL var'
  poll_function_url:
    required: true
    description: 'POLL_VM_URL var'
  iam_token:
    required: true
    description: 'IAM token to use'
  env_file_path:
    required: true
    description: 'Absolute path to a file with job environment'
  secret_files:
    required: false
    default: ''
    description: 'List of secret files (src1:dst,src2:dst2,...) to transfer to the build VM'
  local_out_path:
    required: true
    description: 'Absolute path to desired artifact location'
  remote_out_path:
    required: true
    description: 'Absolute path to artifacts on the VM'
runs:
  using: composite
  steps:
    - name: Create tarball
      run: |
        (cd '${{ inputs.target_checkout }}' && git archive --output=../target.tar.gz HEAD)
      shell: bash
    - name: Create VM and run command
      env:
        IAM_TOKEN: ${{ inputs.iam_token }}
        CREATE_VM_URL: ${{ inputs.start_function_url }}
        POLL_VM_URL: ${{ inputs.poll_function_url }}
        RUN_ID: ${{ github.run_id }}
        REPO_ID: ${{ github.repository_id }}
        ARCHIVE_PATH: ${{ github.workspace }}/target.tar.gz
        SCRIPT_PATH: ${{ inputs.target_checkout }}/perforator/ci/scripts/${{ inputs.script }}.sh
        OUT_PATH: ${{ inputs.local_out_path }}
        REMOTE_OUT_PATH: ${{ inputs.remote_out_path }}
        LOCAL_WORK_DIR: ${{ github.workspace }}/rr-work
        ENV_FILE: ${{ inputs.env_file_path }}
        SECRET_FILES: ${{ inputs.secret_files }}
      run: |
        rm -rf rr-work
        mkdir rr-work
        cd '${{ github.action_path }}/../../..'
        ./ya tool go build ./perforator/internal/ci-tools
        ./ci-tools
      shell: bash
